from rllib.environment.mdp import MDP, Transition

class RandomMDP(MDP):
    def __init__(self, num_states: int = ..., num_actions: int = ...) -> None: ...
    @staticmethod
    def _build_mdp(num_states: int, num_actions: int) -> Transition: ...
