from typing import Any

from torch import Tensor

from rllib.agent.abstract_agent import AbstractAgent
from rllib.dataset.datatypes import Observation
from rllib.model import AbstractModel

def get_target(model: AbstractModel, observation: Observation) -> Tensor: ...
def gaussian_cdf(x: Tensor, mean: Tensor, chol_std: Tensor) -> Tensor: ...
def calibration_count(
    target: Tensor, mean: Tensor, chol_std: Tensor, buckets: Tensor
) -> Tensor: ...
def calibration_score(
    model: AbstractModel, observation: Observation, bins: int = ...
) -> Tensor: ...
def sharpness(model: AbstractModel, observation: Observation) -> Tensor: ...
def model_mse(model: AbstractModel, observation: Observation) -> Tensor: ...
def model_loss(model: AbstractModel, observation: Observation) -> Tensor: ...

class Evaluate(object):
    agent: AbstractAgent
    def __init__(self, agent: AbstractAgent) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...
