from typing import List
from rllib.util.utilities import MovingAverage

class EarlyStopping(object):
    epsilon: float
    relative: bool
    moving_average: List[MovingAverage]
    min_value: List[float]
    def __init__(self, epsilon: float, relative: bool = ...) -> None: ...
    @property
    def stop(self) -> bool: ...
    def _reset(self, num: int, hard: bool) -> None: ...
    def reset(self, hard: bool = ...) -> None: ...
    def update(self, *args: float) -> None: ...
