from abc import ABCMeta
from typing import Optional

import torch.nn as nn

class ParameterDecay(nn.Module, metaclass=ABCMeta):
    start: nn.Parameter
    end: nn.Parameter
    decay: nn.Parameter
    step: int
    def __init__(
        self, start: float, end: Optional[float] = ..., decay: Optional[float] = ...
    ) -> None: ...
    def update(self) -> None: ...

class Constant(ParameterDecay): ...

class Learnable(ParameterDecay):
    positive: bool
    def __init__(self, start: float, positive: Optional[bool] = ...) -> None: ...

class ExponentialDecay(ParameterDecay): ...
class PolynomialDecay(ParameterDecay): ...
class LinearDecay(ParameterDecay): ...
class LinearGrowth(ParameterDecay): ...
