from rllib.dataset.datatypes import Distribution, Array, Gaussian
from typing import Callable, Tuple
from torch import Tensor

def mellow_max(values: Array, omega: float = 1.) -> Array: ...

def integrate(function: Callable, distribution: Distribution, num_samples: int = 1) -> Tensor: ...

def discount_cumsum(returns: Array, gamma: float = 1.0) -> Array: ...

def moving_average_filter(x: Array, y: Array, horizon: int) -> Array: ...

def separated_kl(p: Gaussian, q: Gaussian) -> Tuple[Tensor, Tensor]: ...